language: python
cache:
  directories:
  - node_modules
script:
- npm install -g serverless
- pushd backend/api/blogs
- sls deploy -v | tee deploy.out
- export $(cat deploy.out | grep POST | awk -F" - " '{ print "BASE_URL="$2 }' | sed 's/\/api.*//g')  # Export base_url for tests
- popd
- pushd backend/tests
- pip install pipenv
- pipenv install
- pipenv run py.test
env:
  global:
  - secure: iCIVQdBnClbSDS3A092rr5PJsqy0lVZC/5ZKXBCnHZSr3ALofOWeRugW1sZcvZ1sVQ3ecMFzp3TK92UtA0qbuT9Fv10+KcEOyo3maItIa8LJ6XDK3R+lRzYeJ2kNoG7/9EqD8h8fbXn5hjaeCud4dD2Qz4HMYS90xd30Tb/y0hGOmwkqhuotjnoDgYo12/U/NNOz6pCUa0BOKIMTbjfcdjc1P1RLrpoc3i+NVwDnaImOAgEVMzrBi5/4W5O5SyTKHqEHVSfFKA3mPyiONX6/rASMrBrHjP09XTnaLgIcmD+FgTTFhPB6rgbLPLuqPVCCscMX12sOdFj8OBCW8/05ycAxpTAmw9UC8O0R9cyjfZtfHRVdB+OQnh9+lwix4Wg7feG/pg3nfXmCwqLZhT461fJAgwKtIkkDXu3beEOKeQoWzIrVj2UWgF6T3DDHslNeiYH8RT5gQDdi3SXJw8PfHSL+yjIRFWG6xbOd3kRURFCMGqdHzffdHx+R5Qh95xCdx6HTelAAYwIKmh6VonINrknXN0YVe9IQlv9FKl0Mka402xN0pSjbs/QBUQO1fAo6XOlQu64R54VI2ZkrPaZ8+LRWyUqxXEU5/zefVJc0G7gPHNbSiMta8iFKFTpshVoNowHsV5z8vzpOBqzcyAy9ovwKuVu/rLJ4yS0rh9fyFqU=
  - secure: XkTLBMpZt9LmYQIwTwQbG7XTpw/QPkM0ilDAcbpPSyJCOACjaUuLSdVnbhuERT3yTOZtucZxRrY/D4DooZdud8D0+azLh/UYe3vnRxAvedeM1Awyc3G3Bh1BofDvSOYsdHc8Nkg12RIrMAEdWyMxn5pZczKd3W6+yZuntfd8fe7BV42/6Sa5Elxo1zQ4sBdouxn4rBcVbdT2Qg5l9eJKKHGL5hriUpjuwQcHSfiPxKxs4eX2N0qnqMPSrcG6wVk4mO1TyIoKKkNGwZdTonCGGjkA3SIpf0b/xEIiFEc8SB/mcZrAX0ENHE5jZfh7ld1vWUSapz/jQFFAwvwE6oA108Ig3IwyG5k5RVlLdQoLbgrY0BBc/ctT7a1Z/t2fvPfDod2MASV6mIjCUc4E4BZJZ9N1Z7zSKpguJDY8N3GM56FrzggOIc+r8nqJPbBQtON+U+0PsUHUMBif4inQ9a3NQ3FrUYi0XDyIxO+sgrOfIFKebXDHL5DFm+XufaMcRdNBkKXBaAH0/xXlDbQgfM8Kak4VvlTwd9S91Nv33i1YBcZzmuDcyWbhQvExkDub3y6yTNTIHCEn3nzuEWA9qBdHTJEV7W4n1NYQINFhunajtvF75Tug4Zfoo6Hrz8iaRO8M1otwTjAHscgoWE4XSRuoq1yjTLVVue6TYTFeBY+ja5M=
