version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --prefix frontend
  build:
    commands:
      - echo Build started on `date`
      - npm run --prefix frontend build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 cp --recursive $CODEBUILD_SRC_DIR/frontend/build s3://microtrans-blog/
      - aws s3 cp --acl public-read 
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        $CODEBUILD_SRC_DIR/frontend/build/service-worker.js s3://microtrans-blog/
artifacts:
  files:
    - '**/*'